"""Add users table

Revision ID: 736c795d2baa
Revises: 
Create Date: 2026-03-07 20:33:51.560157

"""
from alembic import op
import sqlalchemy as sa
from models import db, User, Role
from password_handler import hash_password
from config import INIT_ADMIN_PASSWORD


# revision identifiers, used by Alembic.
revision = '736c795d2baa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.Index('ix_roles_users_user_id', 'user_id'),
    sa.Index('ix_roles_users_role_id', 'role_id')
    )

    # CREATE ADMIN

    # Create admin role
    admin_role = Role(name='admin') 
    db.session.add(admin_role)
    db.session.commit()
    
    # Create admin user
    admin_user = User(
        email='admin',
        password=hash_password(INIT_ADMIN_PASSWORD),
        roles=[admin_role],
        active=True,
    )
    db.session.add(admin_user)
    db.session.commit()

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    op.drop_table('user')
    op.drop_table('role')
    # ### end Alembic commands ###
