"""add use_original_as_preview to library

Revision ID: 0c612f250d48
Revises: 6d956a1df43b
Create Date: 2026-03-26 23:07:44.721151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c612f250d48'
down_revision = '6d956a1df43b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_original_as_preview', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.drop_column('use_original_as_preview')

    # ### end Alembic commands ###
