"""add notifications

Revision ID: 145c7909c016
Revises: d3d1f1de06b7
Create Date: 2026-03-18 17:28:58.668294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '145c7909c016'
down_revision = 'd3d1f1de06b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('seen_at', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Enum('library_marked', name='notificationtype'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('related_object', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finished_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.drop_column('finished_at')

    op.drop_table('notification')
    # ### end Alembic commands ###
