"""add public_upload_enabled and is_external

Revision ID: 1b6fb0b5fb32
Revises: 48f8bbfd1198
Create Date: 2026-04-17 14:37:51.035398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b6fb0b5fb32'
down_revision = '48f8bbfd1198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_external', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_upload_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.drop_column('public_upload_enabled')

    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_column('is_external')

    # ### end Alembic commands ###
