"""add watermark fields to library

Revision ID: 350f82113813
Revises: 6ed7681a2344
Create Date: 2026-03-28 20:02:01.942286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '350f82113813'
down_revision = '6ed7681a2344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.add_column(sa.Column('watermark_gcs_key', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('watermark_scale', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('watermark_position', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.drop_column('watermark_position')
        batch_op.drop_column('watermark_scale')
        batch_op.drop_column('watermark_gcs_key')

    # ### end Alembic commands ###
