"""initial

Revision ID: 482fc9a1a659
Revises:
Create Date: 2026-03-13 19:02:58.673586

"""

from alembic import op
import sqlalchemy as sa
from config import INIT_ADMIN_PASSWORD
from password_handler import hash_password

# revision identifiers, used by Alembic.
revision = "482fc9a1a659"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("account_type", sa.String(length=16), nullable=False),
        sa.Column("auth_string", sa.String(length=255), nullable=True),
        sa.Column("max_libraries", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "roles_users",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
    )
    with op.batch_alter_table("roles_users", schema=None) as batch_op:
        batch_op.create_index("ix_roles_users_role_id", ["role_id"], unique=False)
        batch_op.create_index("ix_roles_users_user_id", ["user_id"], unique=False)

    # ### end Alembic commands ###

    bind = op.get_bind()

    bind.execute(sa.text("INSERT INTO role (name) VALUES ('admin')"))
    role_id = bind.execute(sa.text("SELECT id FROM role WHERE name = 'admin'")).scalar()

    from datetime import datetime, timezone

    now = datetime.now(timezone.utc)
    bind.execute(
        sa.text(
            'INSERT INTO "user" (email, active, account_type, auth_string, max_libraries, created_at) '
            "VALUES (:email, true, 'local', :auth_string, 100, :created_at)"
        ),
        {
            "email": "admin",
            "auth_string": hash_password(INIT_ADMIN_PASSWORD),
            "created_at": now,
        },
    )
    user_id = bind.execute(
        sa.text("SELECT id FROM \"user\" WHERE email = 'admin'")
    ).scalar()

    bind.execute(
        sa.text(
            "INSERT INTO roles_users (user_id, role_id) VALUES (:user_id, :role_id)"
        ),
        {"user_id": user_id, "role_id": role_id},
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("roles_users", schema=None) as batch_op:
        batch_op.drop_index("ix_roles_users_user_id")
        batch_op.drop_index("ix_roles_users_role_id")

    op.drop_table("roles_users")
    op.drop_table("user")
    op.drop_table("role")
    # ### end Alembic commands ###
