"""add video table

Revision ID: 625bb3257bba
Revises: 1b6fb0b5fb32
Create Date: 2026-05-10 12:11:19.555374

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "625bb3257bba"
down_revision = "1b6fb0b5fb32"
branch_labels = None
depends_on = None


def upgrade():
    # Add new values to auditlogtype (PostgreSQL requires ALTER TYPE outside transactions)
    op.execute("ALTER TYPE auditlogtype ADD VALUE IF NOT EXISTS 'video_uploaded'")
    op.execute("ALTER TYPE auditlogtype ADD VALUE IF NOT EXISTS 'video_deleted'")
    op.execute("ALTER TYPE auditlogtype ADD VALUE IF NOT EXISTS 'video_downloaded'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "video",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("library_id", sa.Integer(), nullable=False),
        sa.Column("s3_key", sa.String(length=255), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=32), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("video_codec", sa.String(length=32), nullable=True),
        sa.Column("audio_codec", sa.String(length=32), nullable=True),
        sa.Column("bitrate", sa.Integer(), nullable=True),
        sa.Column(
            "processing_status",
            sa.Enum(
                "uploading",
                "processing",
                "ready",
                "failed",
                name="videoprocessingstatus",
            ),
            server_default="uploading",
            nullable=False,
        ),
        sa.Column(
            "hevc_warning",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "customer_state",
            postgresql.ENUM("none", "liked", name="customerstate", create_type=False),
            server_default="none",
            nullable=False,
        ),
        sa.Column(
            "is_external", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["library.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("video", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_video_uuid"), ["uuid"], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("video", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_video_uuid"))

    op.drop_table("video")
    # ### end Alembic commands ###
