"""add libraries

Revision ID: 996690c28992
Revises: b3c4d5e6f7a8
Create Date: 2026-03-14 13:21:53.731972

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "996690c28992"
down_revision = "b3c4d5e6f7a8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "library",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("archived_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("library", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_library_uuid"), ["uuid"], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("library", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_library_uuid"))

    op.drop_table("library")
    # ### end Alembic commands ###
