"""add agb acceptance tracking

Revision ID: dc1136b580db
Revises: 5da59d638613
Create Date: 2026-03-29 18:32:54.344519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc1136b580db'
down_revision = '5da59d638613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agb_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('notified_at', sa.DateTime(), nullable=False),
    sa.Column('effective_at', sa.DateTime(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agb_updates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agb_updates_notified_at'), ['notified_at'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agb_accepted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('agb_version', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('agb_version')
        batch_op.drop_column('agb_accepted_at')

    with op.batch_alter_table('agb_updates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agb_updates_notified_at'))

    op.drop_table('agb_updates')
    # ### end Alembic commands ###
