[loggers]
keys=root,gunicorn.error,gunicorn.access

[handlers]
keys=console

[formatters]
keys=json

[logger_root]
level=WARNING
handlers=console

[logger_gunicorn.error]
level=INFO
handlers=console
qualname=gunicorn.error
propagate=0

[logger_gunicorn.access]
level=INFO
handlers=console
qualname=gunicorn.access
propagate=0

[handler_console]
class=StreamHandler
args=(sys.stdout,)
formatter=json

[formatter_json]
class=log.JsonFormatter
