/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibraryLibraryUuidRouteImport } from './routes/library.$libraryUuid'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryLibraryUuidRoute = LibraryLibraryUuidRouteImport.update({
  id: '/library/$libraryUuid',
  path: '/library/$libraryUuid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/activate': typeof ActivateRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/support': typeof SupportRoute
  '/library/$libraryUuid': typeof LibraryLibraryUuidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/activate': typeof ActivateRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/support': typeof SupportRoute
  '/library/$libraryUuid': typeof LibraryLibraryUuidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/activate': typeof ActivateRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/support': typeof SupportRoute
  '/library/$libraryUuid': typeof LibraryLibraryUuidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/activate'
    | '/login'
    | '/register'
    | '/support'
    | '/library/$libraryUuid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/activate'
    | '/login'
    | '/register'
    | '/support'
    | '/library/$libraryUuid'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/activate'
    | '/login'
    | '/register'
    | '/support'
    | '/library/$libraryUuid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ActivateRoute: typeof ActivateRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SupportRoute: typeof SupportRoute
  LibraryLibraryUuidRoute: typeof LibraryLibraryUuidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$libraryUuid': {
      id: '/library/$libraryUuid'
      path: '/library/$libraryUuid'
      fullPath: '/library/$libraryUuid'
      preLoaderRoute: typeof LibraryLibraryUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ActivateRoute: ActivateRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SupportRoute: SupportRoute,
  LibraryLibraryUuidRoute: LibraryLibraryUuidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
