/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AccountRouteImport } from './routes/account'
import { Route as SupportRouteImport } from './routes/support'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibraryLibraryUuidRouteImport } from './routes/library.$libraryUuid'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryLibraryUuidRoute = LibraryLibraryUuidRouteImport.update({
  id: '/library/$libraryUuid',
  path: '/library/$libraryUuid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/support': typeof SupportRoute
  '/login': typeof LoginRoute
  '/library/$libraryUuid': typeof LibraryLibraryUuidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/support': typeof SupportRoute
  '/login': typeof LoginRoute
  '/library/$libraryUuid': typeof LibraryLibraryUuidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/support': typeof SupportRoute
  '/login': typeof LoginRoute
  '/library/$libraryUuid': typeof LibraryLibraryUuidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/account' | '/support' | '/login' | '/library/$libraryUuid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/account' | '/support' | '/login' | '/library/$libraryUuid'
  id: '__root__' | '/' | '/account' | '/support' | '/login' | '/library/$libraryUuid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  SupportRoute: typeof SupportRoute
  LoginRoute: typeof LoginRoute
  LibraryLibraryUuidRoute: typeof LibraryLibraryUuidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$libraryUuid': {
      id: '/library/$libraryUuid'
      path: '/library/$libraryUuid'
      fullPath: '/library/$libraryUuid'
      preLoaderRoute: typeof LibraryLibraryUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  SupportRoute: SupportRoute,
  LoginRoute: LoginRoute,
  LibraryLibraryUuidRoute: LibraryLibraryUuidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
